### ISSUE TITLE
Error: 'mem.limits' is defunct in R 3.2.3

### ISSUE THREAD

**Issue by thamilt9** [jreps/patientCluster#1]
Hi Jenna,

When I run patientCluster::clusterPeople, I get an error that mem.limits is defunct, and to use 'gc' instead.  I'm on R 3.2.3, and Frank tried it and succeeded in R 3.2.2.  Here's the full output of the run, along with a stacktrace:

```
> clusterCohort(5,1)
Connecting using SQL Server driver
Checking input...
Extracting data...
  |======================================================================| 100%
Analysis took 1.5 mins
Found 92858 cohort people in cohort_id 5
Enough people... Extracting covariate data
Data extracted ...
 Connection successful!

R is connected to the H2O cluster:
    H2O cluster uptime:         1 minutes 42 seconds
    H2O cluster version:        3.8.1.3
    H2O cluster name:           H2O_started_from_R_root_fci451
    H2O cluster total nodes:    1
    H2O cluster total memory:   0.77 GB
    H2O cluster total cores:    15
    H2O cluster allowed cores:  2
    H2O cluster healthy:        TRUE
    H2O Connection ip:          localhost
    H2O Connection port:        54321
    H2O Connection proxy:       NA
    R Version:                  R version 3.2.3 (2015-12-10)

Error: 'mem.limits' is defunct.
Use 'gc' instead.
See help("Defunct")
> traceback()
6: stop(paste(msg, collapse = ""), call. = FALSE, domain = NA)
5: .Defunct("gc")
4: mem.limits(nsize = NA, vsize = NA)
3: paste0(mem.limits(nsize = NA, vsize = NA) * 0.8, "g")
2: patientCluster::clusterPeople(cohort.raw, ffloc = "D:/fftemp")
1: clusterCohort(5, 1)
```

Thanks,
-Taylor

**Comment by jreps** [comment]
Hi Taylor,

Thanks for finding this bug.  I've now edited the code to remove the automatic h2o RAM setting for non-window's users (as I can't test it works from my window's laptop at the moment - when I get on a mac or use linux I'll then test and add a working automatic h2o RAM setting back for non-window's users).  For now this means the error should no longer happen but if you want a non-default h2o ram value you'll need to run this before the clusterPeople(): 
h2o.init(nthreads = -1, max_mem_size = 'the number of gigabytes of ram you want h2o to use followed by g')

For example, to set h2o up using 4 gigs of ram:
h2o.init(nthreads = -1, max_mem_size = '4g')

Best wishes,
Jenna
